### ISSUE TITLE
Cadastramento da Consulta Personalizada na Gestão de Ambientes

### ISSUE THREAD

**Issue by mobilecosta** [mobilecosta/estudosti#1]

**Comment by luanpedro0014** [comment]
Foi realizado o cadastro das tabelas, campos e dos índices. Entretanto ficou algumas pendências.
Segue abaixo:
1) Continuar configurando na tabela generica PQ1(_4).
2) Na tabela PQ2 no campo id==> Consulta padrão PQ1.
3) Tabela PQ8 Criar consulta padrão UGR
4) Tabela PQ8 Criar consulta padrão US2

**Comment by mobilecosta** [comment]
Após avaliação foi identificado que o uso do gestão de ambientes não é o ideal para o momento.
