### ISSUE TITLE
Entendimento dos fontes MVC e execução em ambiente Local

### ISSUE THREAD

**Issue by mobilecosta** [mobilecosta/estudosti#4]
https://github.com/mobilecosta/mvc

**Comment by AdrianoSSantana** [comment]
Criado ambiente no Protheus release27 para estudos e já compilado fontes no ambiente.

**Comment by AdrianoSSantana** [comment]
Erro ao realizar UPDATE das tabelas para estudo;

THREAD ERROR ([18948], adriano.santana, SPON019402578)   21/04/2021   09:51:49
Alias does not exist SX2
( PREVIOUS ERROR : 
Alias does not exist: SM0
 ) on CHKFILE(APLIB200.PRW) 12/03/2021 19:51:53 line : 956


Links com possíveis causas para solução - O erro Alias does not exist SX2 esta relacionado a não preparação do ambiente, desta forma não é possível efetuar a leitura de tabelas e dicionários. 

Deve-se verificar a chave PREPAREIN e no header da requisição verificar se esta sendo enviado o TenantId

https://tdn.totvs.com/display/framework/02.+REST+com+ERP+Microsiga+Protheus

**Comment by AdrianoSSantana** [comment]
Correção na Linha 259 do Fonte UPDMVC

//	RpcClearEnv() - função encerrava ambiente causando o error.log citado anteriormente.

**Comment by AdrianoSSantana** [comment]
Novo error.log apresentado no fonte COMP011_MVC ao clicar em Incluir.

THREAD ERROR ([3176], adriano.santana, SPON019402578)   21/04/2021 15:54:45
erro no parâmetroFWFormModel: Configure a chave primária do modelo para ativar a classe on FWFORMMODEL:ACTIVATE(FWFORMMODEL.PRX) 12/03/2021 19:51:53 line : 398

**Comment by AdrianoSSantana** [comment]
Erro de chave primária do modelo para ativar a classe on FWFORMMODEL:ACTIVATE(FWFORMMODEL.PRX) 12/03/2021 19:51:53 line : 398 corrigido com a inclusão da linha 87

//Setando a chave primária da rotina
oModel:SetPrimaryKey({'ZA0_FILIAL','ZA0_CODIGO'})

**Comment by AdrianoSSantana** [comment]
Novo error.log apresentado no fonte COMP011_MVC ao clicar em Incluir.

THREAD ERROR ([16724], adriano.santana, SPON019402578)   22/04/2021 18:09:19
FWformViewStruct não tem campos associados.
 on FWFORMVIEWSTRUCT:ACTIVATE(FWFORMVIEWSTRUCT.PRW) 12/03/2021 19:51:53 line : 108

**Comment by AdrianoSSantana** [comment]
Erro de FWformViewStruct não tem campos associados corrigido.

Alterado via APSDU tabela SX3 - Tabela (ZA0).

Campo: X3_USADO para: x       x       x       x       x       x       x       x       x       x       x       x       x       x       x x     
Campo: X3_RESERV para:   x  x x        

Motivo do erro é porque em 2009 não havia estrutura de campos de dados no Banco, com isso a estrutura foi criada na forma antiga, causando erros de estrutura nas tabelas.
